[package]
name = "hist2"
version = "0.1.0"
authors = ["sunny"]
edition = "2018"

[dependencies]
iced = { git="https://github.com/hecrj/iced", features = ["canvas", "async-std", "debug"]}
atty = "0.2"
itertools = "0.9.0"
clap = "2.33.3"
